#!/bin/bash
# OBM Webmail Proxy App launcher

appid=fr.aliasource.webmail.proxy.proxyapp


curdir=`dirname $0`
echo -n "equinox shell lib loading..."
source ${curdir}/equinox.lib
echo "[OK]"

aliasource_equinox_profile_server_appid ${curdir} ${appid}
